# Generated by Django 2.2.5 on 2019-09-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msplt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['create_time'], 'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
    ]
