# Generated by Django 2.2.5 on 2019-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msplt', '0002_auto_20190919_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
